### ISSUE TITLE
Utah raptor is bleeding without being damaged.

### ISSUE THREAD

**Issue by MarianaBoni** [deathlyrage/theisle-bugs#90] opened 2017-09-01 00:10 UTC
Patch: 4290
Server: Any,
Utah raptor bleeds without being attacked.
It starts just as a few drops and turns into it spilling more.
![20170901010901_1](https://user-images.githubusercontent.com/30121219/29950244-54218012-8eb2-11e7-8da1-5f667a6bc29a.jpg)
![e01f08e92c4b64f8628c95f448c0f04f](https://user-images.githubusercontent.com/30121219/29950248-584960f6-8eb2-11e7-836a-e521ad431036.jpg)

**Comment by deathlyrage** [comment] 2017-09-04 11:41
Closing, unable to reproduce.

**Closed by deathlyrage** 2017-09-04 11:41 UTC
